preload = /usr/share/backgrounds/gaming-wallpaper.png
preload = /usr/share/backgrounds/wallpaper-2.png
preload = /usr/share/backgrounds/wallpaper-3.png
preload = /usr/share/backgrounds/wallpaper-4.png

wallpaper = ,/usr/share/backgrounds/gaming-wallpaper.png

splash = false
ipc = on
